/**
 * Phrases d'entraînement de Maé : ce que les clientes disent vraiment, en français et en wolof
 * (avec les orthographes courantes). Pour lui apprendre une nouvelle façon de dire, il suffit
 * d'ajouter une phrase dans la bonne liste. Les phrases de contrôle (jamais apprises) sont
 * dans scripts/eval-assistant/examen.mjs.
 */
export type Intent =
  | 'salut'
  | 'merci'
  | 'aurevoir'
  | 'qui'
  | 'cherche'
  | 'prix'
  | 'livraison'
  | 'paiement'
  | 'suivi'
  | 'retour'
  | 'pointure'
  | 'boutique'
  | 'marque'
  | 'promo'
  | 'cadeau'
  | 'commander'
  | 'humain'
  | 'fete'
  | 'moins_cher'
  | 'autres'
  | 'oui'
  | 'non'
  | 'plainte'
  | 'hesite'
  | 'confiance'
  | 'qualite'
  | 'dimensions'
  | 'photos'
  | 'compliment'
  | 'nouveautes'
  | 'gros'
  | 'modifier'
  | 'langue'
  | 'bof';

export const TRAINING: Record<Intent, string[]> = {
  salut: [
    'bonjour',
    'bonsoir',
    'salut',
    'coucou',
    'hello',
    'bonjour madame',
    'bonjour maé',
    'bjr',
    'slt',
    'bonjour comment allez-vous',
    'salam',
    'salaam aleekum',
    'salamalekum',
    'asalamu aleykum',
    'na nga def',
    'nanga def',
    'jamm nga am',
    'jaam nga am',
    'mangi nuyu',
    'maangi nuyu',
    'nuyu naa la',
  ],
  merci: [
    'merci',
    'merci beaucoup',
    'merci bien',
    'merci maé',
    "c'est gentil merci",
    'super merci',
    'ok merci',
    'mci',
    'thanks',
    'jërëjëf',
    'jerejef',
    'dieuredieuf',
    'jarajef',
    'jërëjëf maé',
    'jerejef bu baax',
    'jërëjëf waay',
  ],
  aurevoir: [
    'au revoir',
    'bonne journée',
    'bonne soirée',
    'à bientôt',
    'à plus',
    'bye',
    'bonne nuit',
    'à demain',
    'ba beneen',
    'ba beneen yoon',
    'ba ci kanam',
    'mangi dem',
    'maangi dem',
    'ba suba',
    'ba ci kanam inshallah',
  ],
  qui: [
    'tu es qui',
    'vous êtes qui',
    'qui êtes-vous',
    'tu es un robot',
    "c'est un robot",
    'tu es une vraie personne',
    'je parle à qui',
    "c'est quoi maé",
    'tu es une ia',
    'yow kan nga',
    'kan nga',
    'nit nga walla robot',
    'robot nga',
    'kan mooy wax',
    'yow ana nga',
  ],
  cherche: [
    'je cherche un sac',
    'je veux un sac',
    'je voudrais des chaussures',
    'montrez-moi vos sacs',
    'vous avez des sandales',
    'je cherche des mules',
    'je cherche un sac pour un mariage',
    'un sac noir',
    'des chaussures pour une soirée',
    'je fais du 38 je veux des chaussures',
    'sandales plates en 39',
    'une pochette pour un baptême',
    'je veux quelque chose pour la tabaski',
    'un sac pas cher',
    'un sac à moins de 16000',
    'vous avez quoi en rouge',
    "qu'est-ce que vous avez comme nouveautés",
    'montrez-moi ce que vous avez',
    'je cherche un cadeau pas un sac',
    'des talons pour un mariage',
    'des tongs dorées',
    'je veux voir les sacs à main',
    'conseillez-moi un sac pour le bureau',
    "j'ai besoin de chaussures confortables",
    'avez-vous des mules à talon',
    'un sac bordeaux',
    'dama bëgg sac',
    'dama beug sac',
    'dama bëgg dàll',
    'dama bëgg dall',
    'am ngeen sac',
    'am ngeen dàll',
    'wone ma sac yi',
    'wone ma dàll yi',
    'lan ngeen am',
    'dama bëgg sac ngir céet',
    'dama bëgg dàll ngir ngénte',
    'sac bu ñuul',
    'sac bu xonq',
    'dàll bu weex',
    'sama pointure 38 dama bëgg dàll',
    'sac bu yomb',
    'dama bëgg sac bu rafet',
    'dama wut sac',
    'maa ngi wut dàll',
    'dama bëgg pochette',
    'dama bëgg lu bees',
    'yan sac ngeen am',
  ],
  prix: [
    'combien coûte le sac awa',
    "c'est combien",
    'quel est le prix',
    'le prix du sac ndella',
    'combien pour la pochette',
    'combien les mules',
    'ça coûte combien',
    'prix svp',
    "le sac diarra c'est combien",
    'combien vaut ce sac',
    'donnez-moi le prix',
    'prix des tongs zara',
    'ñaata la',
    'naata la',
    'ñaata lay jar',
    'naata lay jar',
    'sac awa ñaata la',
    'njëgam ñaata la',
    'njeg bi',
    'dàll yi ñaata lañu',
  ],
  livraison: [
    'vous livrez à ziguinchor',
    'livraison keur massar',
    'vous livrez le week-end',
    'vous livrez le dimanche',
    'livraison en casamance',
    'vous livrez à kolda',
    'vous livrez',
    'combien coûte la livraison',
    "la livraison c'est combien",
    'vous livrez à thiès',
    'livraison à touba',
    'les frais de livraison',
    'en combien de temps je suis livrée',
    'délai de livraison',
    'vous livrez en région',
    'livraison gratuite',
    'quand est-ce que je reçois ma commande',
    'vous livrez à mbour',
    'livraison à pikine',
    'je suis à kaolack vous livrez',
    'livraison dakar',
    'combien de jours pour la livraison',
    'ndax dingeen yónnee',
    'dingeen ma ko indil',
    'yónnee bi ñaata la',
    'ñaata fan',
    'ci thiès dingeen yónnee',
    'ci touba dingeen indi',
    'kañ lay agsi',
    'livraison bi ñaata la',
  ],
  paiement: [
    'on paie à la livraison',
    'paiement à la réception',
    'om',
    'orange money',
    'je paye par om',
    'free money',
    'je paye quand je reçois',
    'règlement à la réception',
    'on règle comment',
    'je paie en cash au livreur',
    'je vous règle par orange money',
    'paiement quand le livreur vient',
    'comment payer',
    'je peux payer comment',
    'vous acceptez wave',
    'paiement orange money',
    'je paie à la livraison',
    'on paie comment',
    'quels moyens de paiement',
    'je peux payer en espèces',
    'paiement par carte',
    'je dois payer avant',
    'le numéro wave',
    'payer par wave',
    'naka laay fey',
    'naka lañuy fey',
    'wave mën naa fey',
    'mën naa fey bu ñu ma indilee',
    'fey ak orange money',
    'nimero wave bi',
    'ndax dama wara fey bala',
  ],
  suivi: [
    'le livreur est en retard',
    'toujours rien reçu',
    "ça fait 3 jours j'attends",
    'où est ma commande',
    'suivi de commande',
    "ma commande n'est pas arrivée",
    'je veux suivre ma commande',
    'où en est ma commande',
    'mon colis',
    'le livreur est où',
    'quand arrive ma commande',
    "j'ai commandé hier",
    'statut de ma commande',
    'ma commande MAE-12345',
    'fan la sama commande nekk',
    'sama commande agsiwul',
    'livreur bi fan la nekk',
    'kañ la sama commande di agsi',
    'dama commande demb',
  ],
  retour: [
    'vous reprenez les articles',
    'reprise possible si ça ne va pas',
    'vous acceptez les retours',
    'si ça ne convient pas vous remboursez',
    'je peux vous le rendre',
    'et si la couleur ne me plaît pas',
    'je peux échanger',
    'échange possible',
    'je peux retourner',
    'remboursement',
    'si ça ne me va pas',
    'retour produit',
    'je veux rendre',
    'la pointure ne va pas je peux changer',
    'politique de retour',
    'je peux changer la couleur après',
    "si c'est trop petit",
    'mën naa ko soppi',
    'mën naa ko delloo',
    'bu ma neexul mën naa ko delloo',
    'soppi pointure',
    'bu tuutee mën naa ko soppi',
  ],
  pointure: [
    'quelle pointure choisir',
    'guide des tailles',
    'je ne connais pas ma pointure',
    'ça taille grand ou petit',
    'je suis entre deux pointures',
    'comment connaître ma pointure',
    'les pointures disponibles',
    'vous faites quelles pointures',
    'il existe en 41',
    "jusqu'à quelle pointure",
    'ban pointure laay jël',
    'xamuma sama pointure',
    'pointure yi',
    'ban pointure ngeen am',
    'am na 41',
    'am ngeen 40',
  ],
  boutique: [
    'où est votre boutique',
    'vous êtes où',
    'adresse de la boutique',
    'je peux passer à la boutique',
    'vous avez un magasin',
    "horaires d'ouverture",
    'vous êtes ouverts le dimanche',
    'où vous trouver',
    'je veux venir voir',
    'boutique physique',
    'vous êtes situés où',
    'fan ngeen nekk',
    'fan la boutique bi nekk',
    'mën naa ñëw',
    'ndax am ngeen boutique',
    'kañ ngeen di ubbi',
  ],
  marque: [
    "c'est du vrai hermès",
    "c'est original",
    "c'est de la marque",
    "c'est authentique",
    "c'est une copie",
    "c'est du chanel",
    "c'est du gucci",
    "c'est une contrefaçon",
    'vous vendez des vraies marques',
    "c'est du vrai zara",
    "c'est tods",
    "c'est de la qualité",
    'dëgg la',
    'original la',
    'marque dëgg la',
    'copie la',
    'hermès dëgg la',
  ],
  promo: [
    'vous avez une promo',
    'code promo',
    'réduction',
    'remise',
    'il y a des soldes',
    'vous faites des prix',
    'un bon de réduction',
    'une offre',
    'am na promo',
    'wàññi njëg bi',
    'wanni ma',
    'mën ngeen wàññi',
    'waññi tuuti',
    'am na réduction',
    "c'est quoi le dernier prix",
    'le prix est négociable',
    'on peut négocier',
    'baissez un peu le prix',
    'vous pouvez faire un geste',
    "c'est trop cher pour moi",
    'njëg bi mu mujj',
    'wàññil ma tuuti',
    'mën nañu waxtaan njëg bi',
    'dafa cher',
  ],
  cadeau: [
    'offrir à ma maman',
    'un cadeau pour ma tante',
    'pour faire plaisir à ma sœur',
    'je cherche à offrir',
    'une surprise pour ma copine',
    'offrir pour la fête des mères',
    "c'est pour offrir",
    'idée cadeau',
    'un cadeau pour ma mère',
    'cadeau pour ma femme',
    'emballage cadeau',
    'je veux offrir un sac',
    "cadeau d'anniversaire",
    'quoi offrir',
    'un cadeau pour ma sœur',
    'dama bëgg may',
    'may sama yaay',
    'cadeau ngir sama jabar',
    'cadeau ngir sama doomu ndey',
    'lan laay may',
  ],
  commander: [
    'comment commander',
    'comment on fait pour commander',
    'je veux commander',
    'je veux acheter',
    'comment acheter',
    'je prends celui-là',
    'je veux ce sac',
    'comment passer commande',
    'je le prends',
    'je veux la dorée',
    'ajouter au panier comment',
    "c'est bon je prends",
    'naka laay jënde',
    'dama bëgg jënd',
    'dama koy jënd',
    'naka laay commande',
    'jël naa ko',
    'kii laa bëgg',
    'dama bëgg kii',
  ],
  humain: [
    'votre numéro whatsapp',
    'donnez-moi votre whatsapp',
    'je veux vous écrire sur whatsapp',
    'le contact de la boutique',
    'je peux vous appeler',
    "passez-moi quelqu'un",
    "je veux parler à quelqu'un",
    'parler à une personne',
    'un conseiller',
    'appeler la boutique',
    'votre numéro',
    'whatsapp',
    'je veux appeler',
    'je veux parler à la gérante',
    'contact',
    'numéro de téléphone',
    'dama bëgg wax ak nit',
    'dama bëgg wax ak yeen',
    'nimero bi',
    'woo ma',
    'dama bëgg woo',
    'yónnee ma nimero bi',
  ],
  fete: [
    "c'est quand la tabaski",
    "la korité c'est quand",
    'date du magal',
    'quand est le gamou',
    'la tabaski tombe quand',
    'dans combien de jours la korité',
    'kañ la tabaski',
    'kañ la kori',
    'kan la tabaski',
    'magal bi kañ la',
  ],
  moins_cher: [
    'moins cher',
    "c'est trop cher",
    'vous avez moins cher',
    'plus abordable',
    'un peu moins cher',
    'mon budget est petit',
    'trop cher pour moi',
    'dafa cher',
    'dafa jafe',
    'lu gën a yomb',
    'am na lu yomb',
    'dafa seer',
    'njëg bi dafa rëy',
  ],
  autres: [
    'autre chose',
    "d'autres modèles",
    "montrez-moi d'autres",
    'autres couleurs',
    'vous avez autre chose',
    'pas ça',
    'une autre',
    'encore',
    'leneen',
    'yeneen',
    'wone ma yeneen',
    'am na yeneen',
    'yeneen melo',
    'du kii',
  ],
  oui: [
    'oui',
    'ouais',
    'oui svp',
    "d'accord",
    'ok',
    'volontiers',
    'bien sûr',
    'oui merci',
    'avec plaisir',
    'ça marche',
    'waaw',
    'waw',
    'waaw kay',
    'baax na',
    'mu ngi baax',
    'waaw waaw',
  ],
  non: [
    'non',
    'non merci',
    'pas maintenant',
    'pas besoin',
    'ça ira',
    'plus tard',
    "non c'est bon",
    'déedéet',
    'dedet',
    'deedeet',
    'déedéet jërëjëf',
    'du leegi',
  ],
  plainte: [
    'le produit est cassé',
    "l'article est déchiré",
    'il y a un défaut',
    'le sac est abîmé',
    'reçu en mauvais état',
    'la chaussure est cassée',
    'mauvaise couleur reçue',
    "j'ai un problème",
    'ma commande est abîmée',
    "ce n'est pas ce que j'ai commandé",
    'je ne suis pas contente',
    'le livreur ne répond pas',
    "j'ai payé mais rien",
    'erreur dans ma commande',
    'il manque un article',
    'je veux faire une réclamation',
    'am naa jafe jafe',
    'sama commande dafa yàqu',
    'neexu ma',
    'fey naa waaye dara agsiwul',
    'livreur bi tontuwul',
  ],
  hesite: [
    'je vais réfléchir',
    'je réfléchis',
    'laissez-moi réfléchir',
    'je repasserai',
    'je reviendrai',
    'pas tout de suite',
    'je vais voir',
    'je ne suis pas sûre',
    "j'hésite",
    "j'hésite entre les deux",
    'je vais en parler à mon mari',
    'je vais attendre la fin du mois',
    "quand j'aurai l'argent",
    'dinaa xalaat',
    'dinaa ci xalaat',
    'dinaa délsi',
    'bu ma amee xaalis',
    'xaaral ma tuuti',
    'dama xalaat',
    'bu weer wi jeexee',
  ],
  confiance: [
    "c'est fiable",
    'votre site est fiable',
    'vous êtes sérieux',
    "c'est une arnaque",
    'je peux vous faire confiance',
    "j'ai peur de payer avant",
    'et si je paie et je ne reçois rien',
    'vous existez vraiment',
    "on m'a déjà arnaquée",
    "c'est sécurisé",
    'comment être sûre',
    'dëgg ngeen',
    'mën naa leen woolu',
    'dama ragal fey',
    'bu ma feyee te dara agsiwul',
    'nit ñu dëgg ngeen',
  ],
  qualite: [
    'la qualité est bonne',
    "c'est de bonne qualité",
    "c'est solide",
    "c'est du cuir",
    "c'est en quelle matière",
    'ça dure longtemps',
    "c'est du simili",
    "ça s'abîme vite",
    'les finitions sont bien',
    'la matière est comment',
    'ça tient bien',
    'confortable',
    'dafa dëgër',
    'dafa yàqu gaaw',
    'lan lañu ko def',
    'deru la',
    'dafa neex ci tànk',
  ],
  dimensions: [
    'quelle est la taille du sac',
    'les dimensions',
    'il est grand',
    'il est petit',
    'ça rentre un ipad',
    'on peut mettre un téléphone',
    'combien de centimètres',
    'il est spacieux',
    'contenance du sac',
    'ça rentre des documents a4',
    "c'est lourd",
    'la hauteur du talon',
    'dafa mag',
    'dafa tuuti',
    'telefon mën na ci dugg',
    'naka la réye',
    'talon bi ñaata centimètre',
  ],
  photos: [
    'vous avez des photos portées',
    'je peux voir en vidéo',
    'envoyez-moi plus de photos',
    "c'est la même couleur que sur la photo",
    'photo réelle',
    'je veux voir de plus près',
    'une vidéo du sac',
    "c'est comme sur l'image",
    'autre photo',
    'yónnee ma nataal',
    'dama bëgg gis video',
    'nataal bi dëgg la',
    'melo bi ni mu mel ci nataal bi',
  ],
  compliment: [
    'jaime',
    'jaime bien',
    'jaime beaucoup',
    'ça me plaît',
    'elle me plaît',
    'il me plaît bien',
    'je kiffe',
    'magnifique',
    'trop beau',
    'trop belle',
    "j'aime bien",
    "j'adore",
    'waouh',
    'wow',
    "c'est joli",
    'superbe',
    'il est beau ce sac',
    'elles sont belles',
    'très chic',
    'coup de cœur',
    "c'est top",
    'dafa rafet',
    'rafet na',
    'rafet na lool',
    'neex na',
    'dafa neex',
    'bëgg naa ko',
    'dafa sell',
  ],
  nouveautes: [
    'quoi de neuf',
    'les nouveautés',
    'quels sont les nouveautés',
    'nouveaux arrivages',
    "ce qui vient d'arriver",
    'votre meilleure vente',
    'ce qui marche le plus',
    'les plus demandés',
    'vos best-sellers',
    "qu'est-ce que vous me conseillez",
    'votre coup de cœur',
    'nouvelle collection',
    'lu bees',
    'yu bees yi',
    'lan mooy bees',
    'lan la nit ñi gën a jënd',
    'lan nga ma digal',
  ],
  gros: [
    'je suis revendeuse',
    'prix de gros',
    'je veux acheter en gros',
    'vous faites des prix pour plusieurs',
    'je veux 10 sacs',
    'prix pour une grande quantité',
    'je veux revendre',
    'tarif revendeur',
    'commande en quantité',
    'dama bëgg jënd bu bare',
    'dama jaaykat',
    'njëgu jaaykat',
    'fukk sac laa bëgg',
  ],
  modifier: [
    'annuler ma commande',
    'je veux annuler',
    'changer mon adresse',
    'modifier ma commande',
    'changer la couleur de ma commande',
    'je me suis trompée de pointure',
    'changer le numéro',
    'ajouter un article à ma commande',
    'je veux changer de modèle avant la livraison',
    'dama bëgg dindi sama commande',
    'soppi sama adresse',
    'soppi sama commande',
    'dama juum ci pointure bi',
  ],
  langue: [
    'tu parles wolof',
    'vous parlez wolof',
    'parle français',
    'en français svp',
    'english please',
    'do you speak english',
    'parlez en wolof',
    'wax ma ci wolof',
    'wolof rekk',
    'dégg nga wolof',
    'wax ci français',
    'dégguma français',
  ],
  bof: [
    'cc',
    'yo',
    'hmm',
    'mmm',
    'lol',
    'mdr',
    'haha',
    '?',
    '??',
    'euh',
    'bon',
    'ah bon',
    "d'acc",
    'ah',
    'oh',
    'hein',
    'rien',
    'rien merci',
    'je sais pas',
    'je ne sais pas',
    "pas d'idée",
    'xamuma',
    'dara',
    'dara la',
    'ahh',
    'waaw rekk',
  ],
};

/**
 * Mots-indices par intention (expertise linguistique, français + wolof) : ils complètent l'apprentissage
 * statistique quand les exemples sont peu nombreux. Écrits en clair, normalisés automatiquement.
 */
export const CUES: Partial<Record<Intent, string[]>> = {
  dimensions: [
    'dimension',
    'dimensions',
    'centimètre',
    'centimètres',
    'cm',
    'lourd',
    'spacieux',
    'contenance',
    'mesure',
    'mesures',
    'hauteur',
    'rentre',
    'rentrer',
    'ipad',
    'ordinateur',
    'a4',
    'taille du sac',
    'grand ce sac',
    'réy',
    'dugg',
  ],
  plainte: [
    'cassé',
    'cassée',
    'abîmé',
    'abîmée',
    'déchiré',
    'déchirée',
    'défaut',
    'réclamation',
    'problème',
    'erreur',
    'manque',
    'pas contente',
    'mécontente',
    'mauvais état',
    'yàqu',
    'jafe jafe',
    'neexu ma',
    'tontuwul',
  ],
  qualite: [
    'qualité',
    'solide',
    'cuir',
    'matière',
    'simili',
    'dure',
    'durer',
    'finitions',
    'confortable',
    'dëgër',
    'deru',
    'tient',
  ],
  confiance: [
    'fiable',
    'sérieux',
    'sérieuse',
    'arnaque',
    'arnaquée',
    'escroc',
    'escrocs',
    'confiance',
    'peur',
    'sécurisé',
    'sûre',
    'existez',
    'ragal',
    'woolu',
    'nax',
  ],
  nouveautes: [
    'nouveauté',
    'nouveautés',
    'neuf',
    'arrivage',
    'arrivages',
    'arriver',
    'meilleure vente',
    'plus vendu',
    'best',
    'collection',
    'bees',
    'plus demandés',
  ],
  moins_cher: ['moins cher', 'trop cher', 'cher', 'abordable', 'budget est petit', 'seer', 'rëy', 'gën a yomb'],
  photos: ['photo', 'photos', 'vidéo', 'video', 'image', 'nataal', 'portées'],
  modifier: [
    'annuler',
    'annulation',
    'modifier',
    'changer mon adresse',
    'changer la commande',
    'trompée',
    'dindi',
    'juum',
    'soppi sama commande',
  ],
  compliment: [
    'magnifique',
    'trop beau',
    'trop belle',
    'joli',
    'jolie',
    'superbe',
    'adore',
    'kiffe',
    'top',
    'sublime',
    'rafet na',
    'dafa rafet',
    'neex na',
  ],
  gros: ['gros', 'revendeuse', 'revendre', 'revendeur', 'quantité', 'plusieurs', 'jaaykat', 'bu bare'],
  promo: ['promo', 'promotion', 'code', 'réduction', 'remise', 'soldes', 'offre', 'wàññi'],
  retour: ['échanger', 'échange', 'retour', 'retourner', 'rembourser', 'remboursement', 'reprenez', 'rendre', 'delloo'],
  hesite: [
    'réfléchir',
    'réfléchis',
    'hésite',
    'repasserai',
    'reviendrai',
    'mon mari',
    'mon époux',
    'xalaat',
    'délsi',
    'xaaral',
    'penser',
  ],
  boutique: ['boutique', 'magasin', 'adresse', 'horaires', 'ouvert', 'ouverts', 'situés', 'venir voir', 'ñëw', 'ubbi'],
  commander: [
    'commander',
    'acheter',
    'je prends',
    'je le prends',
    'je la prends',
    'jënd',
    'jël',
    'passer commande',
    'kii laa bëgg',
  ],
  humain: [
    'parler',
    'numéro',
    'appeler',
    'whatsapp',
    'contact',
    'conseiller',
    'conseillère',
    'gérante',
    'woo',
    'wax ak nit',
    'wax ak yeen',
  ],
  aurevoir: [
    'au revoir',
    'bye',
    'à bientôt',
    'à demain',
    'à plus',
    'bonne journée',
    'bonne soirée',
    'bonne nuit',
    'ba beneen',
    'ba suba',
    'mangi dem',
  ],
  qui: ['robot', 'ia', 'machine', 'vraie personne', 'qui êtes', 'es qui', 'kan nga', 'kan mooy'],
  paiement: [
    'payer',
    'paie',
    'paye',
    'paiement',
    'wave',
    'orange money',
    'om',
    'espèces',
    'cash',
    'carte',
    'règle',
    'régler',
    'fey',
  ],
  salut: [
    'bonjour',
    'bonsoir',
    'salut',
    'coucou',
    'hello',
    'bjr',
    'slt',
    'salam',
    'salaam',
    'aleekum',
    'na nga def',
    'nanga def',
  ],
  suivi: [
    'ma commande',
    'colis',
    'suivi',
    'suivre',
    'livreur',
    'pas arrivée',
    'toujours rien',
    'sama commande',
    'agsiwul',
  ],
  pointure: ['pointure', 'pointures', 'taille grand', 'taille petit', 'guide des tailles'],
  marque: [
    'marque',
    'original',
    'authentique',
    'copie',
    'contrefaçon',
    'vrai hermès',
    'hermès',
    'chanel',
    'gucci',
    'tods',
    'dëgg la',
  ],
  autres: ['autre', 'autres', 'encore', 'yeneen', 'leneen'],
  cadeau: ['cadeau', 'offrir', 'may', 'anniversaire', 'surprise'],
  merci: ['merci', 'mci', 'thanks', 'jërëjëf', 'jarajëf'],
  livraison: ['livrer', 'livraison', 'livrez', 'délai', 'yónnee', 'indil'],
  prix: ['prix', 'combien', 'coûte', 'ñaata', 'njëg', 'njëgam'],
  fete: ['tabaski', 'korité', 'magal', 'gamou', 'kori'],
  non: ['non', 'déedéet', 'pas maintenant', 'pas besoin', 'du léegi'],
  oui: ['oui', 'ouais', 'volontiers', 'bien sûr', 'd accord', 'waaw'],
  cherche: ['cherche', 'montrez', 'wut', 'wone ma'],
};
