const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const fs = require('fs'), crypto = require('crypto');
const SP = process.env.SP, B = 'http://localhost:8787', O = SP + '/motion3';
const imgs = fs.readdirSync(SP + '/photos').map(f => fs.readFileSync(SP + '/photos/' + f));
(async () => { const b = await chromium.launch();
  const c = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true, serviceWorkers: 'block' });
  await c.route('https://images.pexels.com/**', r => { const h = parseInt(crypto.createHash('md5').update(r.request().url().split('?')[0]).digest('hex').slice(0, 6), 16); r.fulfill({ contentType: 'image/jpeg', body: imgs[h % imgs.length] }); });
  await c.addInitScript(() => { try { localStorage.setItem('maefa_install_banner', String(Date.now())); sessionStorage.setItem('maefa_assistant_hint', '1'); } catch {}
    document.addEventListener('DOMContentLoaded', () => { const s = document.createElement('style'); s.textContent = '.reveal{opacity:1!important;transform:none!important}html{scroll-behavior:auto!important}*{animation-duration:0s!important;transition-duration:0s!important}'; document.head.appendChild(s); }); });
  const p = await c.newPage();
  const el = async (loc, name) => { await loc.scrollIntoViewIfNeeded(); await p.waitForTimeout(300); await loc.screenshot({ path: `${O}/el/${name}.png`, omitBackground: true }); console.log('OK', name, JSON.stringify(await loc.boundingBox())); };
  await p.goto(B + '/produit/sac-a-main-fatou', { waitUntil: 'networkidle' }); await p.waitForTimeout(1200);
  await p.evaluate(() => document.querySelectorAll('body *').forEach(e => { if (getComputedStyle(e).position === 'fixed') e.style.visibility = 'hidden'; }));
  await el(p.getByTestId('detail-price'), 'price');
  await el(p.locator('p.field-label', { hasText: 'Couleur' }).locator('xpath=..'), 'colors');
  await el(p.getByRole('button', { name: 'Ajouter au panier' }), 'add');
  await el(p.getByText('Commander sur WhatsApp').first(), 'whatsapp');
  await el(p.locator('h1').first(), 'title');
  await p.evaluate(() => document.querySelectorAll('body *').forEach(e => { if (e.style.visibility === 'hidden') e.style.visibility = ''; }));
  await p.getByRole('button', { name: /Ajouter au panier/ }).first().click(); await p.waitForTimeout(1200);
  await p.goto(B + '/commande', { waitUntil: 'networkidle' }); await p.waitForTimeout(900);
  await p.getByLabel('Prénom *').fill('Awa'); await p.getByLabel('Nom *', { exact: true }).fill('Diop'); await p.getByLabel('Téléphone *').fill('77 123 45 67'); await p.getByLabel(/Adresse écrite/).fill('Villa 12, Sacré-Cœur 3');
  await p.getByRole('button', { name: 'Continuer vers le paiement' }).click(); await p.waitForTimeout(800);
  const labels = p.locator('label:has(input[name=payment])');
  const names = ['wave', 'om', 'card', 'cash'];
  for (let i = 0; i < await labels.count() && i < 4; i++) await el(labels.nth(i), 'pay-' + names[i]);
  await p.evaluate(() => scrollTo(0, 0)); await p.waitForTimeout(300);
  await p.getByRole('button', { name: /^Payer/ }).click(); await p.waitForURL(/confirmation/, { timeout: 10000 }); await p.waitForTimeout(1800);
  await p.evaluate(() => scrollTo(0, 0)); await p.waitForTimeout(500);
  const c2 = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, serviceWorkers: 'block' });
  await p.screenshot({ path: `${O}/shots/confirmation3x.png` });
  await el(p.locator('h1').first(), 'merci');
  await b.close(); })().catch(e => { console.log('ERR', e.message); process.exit(1); });
